import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;

import javax.swing.JFrame;

public class main extends javax.swing.JFrame {

    /**
     * Creates new form 
     
     
     */
    /*public main(person a,person b) {
        initComponents(a,b);
    }
    public main() {
        initComponents();
    }*/
    public main(ArrayList<person> list) {
    	initComponents(list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents(ArrayList<person> list) {
    	kisiler_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTable1.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent arg0) {
        		setVisible(false);
        		personal p = new personal(list);
        		//p.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        		p.setSize(700, 600);
        		p.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        	    p.setVisible(true);
        		centreWindow(p);
        	}
        });
        borc_btn = new javax.swing.JButton();
        
        borc_btn.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        	
        		setVisible(false);
        		EventQueue.invokeLater(new Runnable() {
        			public void run() {
        				try {
        					borclar window = new borclar(list);
        					window.frmAidatlar.setVisible(true);
        					//centreWindow(window.frmAidatlar);
        				} catch (Exception e) {
        					e.printStackTrace();
        				}
        			}
        		});
        		
        	}
        });
        aidat_btn = new javax.swing.JButton();
        aidat_btn.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		  
        		setVisible(false);
        		
        		try {
        	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        	                if ("Windows".equals(info.getName())) {
        	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
        	                    break;
        	                }
        	            }
        	        } catch (ClassNotFoundException ex) {
        	            java.util.logging.Logger.getLogger(aidatlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        	        } catch (InstantiationException ex) {
        	            java.util.logging.Logger.getLogger(aidatlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        	        } catch (IllegalAccessException ex) {
        	            java.util.logging.Logger.getLogger(aidatlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        	            java.util.logging.Logger.getLogger(aidatlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        	        }
        	        //</editor-fold>
        	        //</editor-fold>

        	        /* Create and display the form */
        	        java.awt.EventQueue.invokeLater(new Runnable() {
        	            public void run() {
        					aidatlar window = new aidatlar(list);
        					window.frmAidatlar.setVisible(true);
        	            }
        	        });
        	}
        });
        dosya_btn = new javax.swing.JButton();
        dosya_btn.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent arg0) {
        		setVisible(false);
        		Excel_Form exc = new Excel_Form(list);
        		exc.setVisible(true);
        		centreWindow(exc);
        	}
        });
        exit_btn = new javax.swing.JButton();
        kimlik_txtf = new javax.swing.JTextField();
        kisiler_lbl = new javax.swing.JLabel();
        ara_btn = new javax.swing.JButton();

        //jLabel1.setText("jLabel1");

        kisiler_btn.setBackground(javax.swing.UIManager.getDefaults().getColor("EditorPane.foreground"));
        kisiler_btn.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        kisiler_btn.setForeground(new java.awt.Color(0, 0, 255));
        kisiler_btn.setText("Kişiler");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBox.foreground"));
        setForeground(new java.awt.Color(255, 255, 51));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(null);
        
        Object[][] o=new Object[list.size()][3];
        for (int count=0;count<list.size();count++) {
        	o[count][0]=list.get(count).ad_lbl.split(" ")[0];
        	o[count][1]=list.get(count).ad_lbl.split(" ")[1];
        	o[count][2]=list.get(count).getKimlikNo_lbl();
        }
        String[] s= {"Ad", "Soyad", "T.C Kimlik No"};
        jTable1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION))));
        jTable1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(o,s));
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 102));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);
        jScrollPane1.setBounds(10, 71, 773, 245);
        getContentPane().add(jScrollPane1);

        borc_btn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        borc_btn.setText("Borcu olanları görüntüle");
        borc_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        borc_btn.setPreferredSize(new java.awt.Dimension(161, 23));
        borc_btn.setBounds(10, 347, 161, 23);
        getContentPane().add(borc_btn);

        aidat_btn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        aidat_btn.setText("Ödenen aidatları görüntüle");
        aidat_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        aidat_btn.setBounds(215, 348, 160, 21);
        getContentPane().add(aidat_btn);

        dosya_btn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dosya_btn.setText("Dosya ekle");
        dosya_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        dosya_btn.setMinimumSize(new java.awt.Dimension(161, 23));
        dosya_btn.setPreferredSize(new java.awt.Dimension(161, 23));
        dosya_btn.setBounds(453, 347, 161, 23);
        getContentPane().add(dosya_btn);

        exit_btn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        exit_btn.setText("Çıkış ");
        exit_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        exit_btn.setMinimumSize(new java.awt.Dimension(161, 23));
        exit_btn.setPreferredSize(new java.awt.Dimension(161, 23));
        exit_btn.setBounds(659, 347, 100, 23);
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit_btn);

        kimlik_txtf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kimlik_txtf.setText("T.C Kimlik No ");
        kimlik_txtf.setBounds(480, 30, 220, 25);
        kimlik_txtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kimlikActionPerformed(evt);
            }
        });
        getContentPane().add(kimlik_txtf);

        kisiler_lbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        kisiler_lbl.setText("Kişiler");
        kisiler_lbl.setBounds(41, 24, 145, 29);
        getContentPane().add(kisiler_lbl);

        ara_btn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ara_btn.setText("Ara");
        ara_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ara_btn.setBounds(710, 30, 35, 25);
        getContentPane().add(ara_btn);

        pack();
    }// </editor-fold>                        
  
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {    
    	setVisible(false);
        // TODO add your handling code here:
    	
    }                                        

    private void kimlikActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           
    public static void centreWindow(JFrame frame) {
	    Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
	    int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
	    int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
	    frame.setLocation(x, y);
	}
    
    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify                     
    private javax.swing.JButton kisiler_btn;
    private javax.swing.JButton borc_btn;
    private javax.swing.JButton aidat_btn;
    private javax.swing.JButton dosya_btn;
    private javax.swing.JButton exit_btn;
    private javax.swing.JButton ara_btn;
    //private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel kisiler_lbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField kimlik_txtf;
    // End of variables declaration                   
}
